name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - dev

permissions:
  pull-requests: read

jobs:
  validate-pr:
    name: Pull Request Validate
    runs-on: ubuntu-latest
    steps:
      - uses: SthoreH/shd-github-actions-workflows/actions/validate-pr@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          validate-title: "true"
          validate-description: "false"
